 <?php

$dictionary['Meeting']['fields']['assigned_user_name']['reportable'] = true;
$dictionary['Meeting']['fields']['parent_name']['reportable'] = true;
$dictionary['Meeting']['fields']['description']['reportable'] = true;
$dictionary['Meeting']['fields']['parent_type']['reportable'] = true;
$dictionary['Meeting']['fields']['parent_id']['reportable'] = true;


$dictionary['Meeting']['fields']['icc_image1'] = array (
  'dependency' => '',
  'required' => false,
  'name' => 'icc_image1',
  'vname' => 'LBL_ICC_IMAGE1',
  'type' => 'image',
  'massupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => 1,
  'audited' => false,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'calculated' => false,
  'len' => 255,
  'size' => '20',
  'studio' => 'visible',
  'dbType' => 'varchar',
  'width' => '120',
);

$dictionary['Meeting']['fields']['icc_image2'] = array (
  'dependency' => '',
  'required' => false,
  'name' => 'icc_image2',
  'vname' => 'LBL_ICC_IMAGE2',
  'type' => 'image',
  'massupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => 1,
  'audited' => false,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'calculated' => false,
  'len' => 255,
  'size' => '20',
  'studio' => 'visible',
  'dbType' => 'varchar',
  'width' => '120',
);

$dictionary['Meeting']['fields']['icc_image3'] = array (
  'dependency' => '',
  'required' => false,
  'name' => 'icc_image3',
  'vname' => 'LBL_ICC_IMAGE3',
  'type' => 'image',
  'massupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => 1,
  'audited' => false,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'calculated' => false,
  'len' => 255,
  'size' => '20',
  'studio' => 'visible',
  'dbType' => 'varchar',
  'width' => '120',
);

$dictionary['Meeting']['fields']['icc_image4'] = array (
  'dependency' => '',
  'required' => false,
  'name' => 'icc_image4',
  'vname' => 'LBL_ICC_IMAGE4',
  'type' => 'image',
  'massupdate' => false,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'enabled',
  'duplicate_merge_dom_value' => 1,
  'audited' => false,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'pii' => false,
  'calculated' => false,
  'len' => 255,
  'size' => '20',
  'studio' => 'visible',
  'dbType' => 'varchar',
  'width' => '120',
);
