<?php

$dictionary['Opportunity']['fields']['confidence_level']['duplicate_merge_dom_value']='0';
$dictionary['Opportunity']['fields']['confidence_level']['calculated']=false;
$dictionary['Opportunity']['fields']['confidence_level']['required']=false;
$dictionary['Opportunity']['fields']['confidence_level']['name']='confidence_level';
$dictionary['Opportunity']['fields']['confidence_level']['vname']='LBL_CONFIDENCE_LEVEL';
$dictionary['Opportunity']['fields']['confidence_level']['type']='Ratingfield';
$dictionary['Opportunity']['fields']['confidence_level']['massupdate']=false;
$dictionary['Opportunity']['fields']['confidence_level']['hidemassupdate']=false;
$dictionary['Opportunity']['fields']['confidence_level']['no_default']=false;
$dictionary['Opportunity']['fields']['confidence_level']['comments']='';
$dictionary['Opportunity']['fields']['confidence_level']['help']='';
$dictionary['Opportunity']['fields']['confidence_level']['importable']='false';
$dictionary['Opportunity']['fields']['confidence_level']['duplicate_merge']='disabled';
$dictionary['Opportunity']['fields']['confidence_level']['audited']=false;
$dictionary['Opportunity']['fields']['confidence_level']['reportable']=true;
$dictionary['Opportunity']['fields']['confidence_level']['unified_search']=false;
$dictionary['Opportunity']['fields']['confidence_level']['merge_filter']='disabled';
$dictionary['Opportunity']['fields']['confidence_level']['size']='20';
$dictionary['Opportunity']['fields']['confidence_level']['color']='#ffd700';
$dictionary['Opportunity']['fields']['confidence_level']['dbType']='varchar';
